name: Deploy to GitHub Pages
on:
  push:
    branches: ["main"]
    paths-ignore:
      - 'README.md'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v3
      - run: echo "Deploying without README.md changes"